dubbo:
  application:
    name: user-service-provider
  registry:
  #注册中心协议
    protocol: zookeeper
    #注册中心的地址
    address: localhost:2181
  protocol:
    name: dubbo
    port: 20881
  monitor:
  #指定注册中心也是监控中心
    protocol: registry


