spring:
  application:
    name: jwt-security

server:
  port: 8016

jwt:
  # 加密密钥
  secret: iwqjhda8232bjgh432[cicada-smile]
  # token有效时长
  expire: 3600
  #请求头参数
  tokenHead: token

#不需要认证的接口地址
security:
  ignore:
   get:
     - /test/image/**
   post:

   all:


