spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jdbctest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=GMT%2b8&characterEncoding=utf8&connectTimeout=1000&socketTimeout=15000&autoReconnect=true
    #MySQL5.7以上的版本使用com.mysql.cj.jdbc.Driver
    #MySQL5.7以下的版本使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池名称
      pool-name: MyHikariCP
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #连接池最大连接数，默认是10 (cpu核数量 * 2 + 硬盘数量)
      maximum-pool-size: 30
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 600000
      #连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 1800000
      #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 30000
      #用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1